version: '3.8'

services:
  postgres-db:
    build: .
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork: